export type ChinaCity = {
  id: string;
  name: string;
  province: string;
  longitude: number;
  latitude: number;
  visited: boolean;
  labelPosition?: "above" | "below" | "left" | "right";
  memoryType?: string;
  story?: string;
};

export const chinaCities: readonly ChinaCity[] = [
  { id: "urumqi", name: "乌鲁木齐", province: "新疆", longitude: 87.62, latitude: 43.79, visited: false },
  { id: "lhasa", name: "拉萨", province: "西藏", longitude: 91.13, latitude: 29.66, visited: false },
  { id: "lanzhou", name: "兰州", province: "甘肃", longitude: 103.83, latitude: 36.06, visited: false },
  { id: "xian", name: "西安", province: "陕西", longitude: 108.94, latitude: 34.34, visited: false },
  { id: "chengdu", name: "成都", province: "四川", longitude: 104.07, latitude: 30.57, visited: false },
  { id: "chongqing", name: "重庆", province: "重庆", longitude: 106.55, latitude: 29.56, visited: false },
  {
    id: "kunming",
    name: "昆明",
    province: "云南",
    longitude: 102.83,
    latitude: 24.88,
    visited: true,
    labelPosition: "left",
    memoryType: "高原与日常",
    story: "高原的光线和舒缓的气候，让行走本身变得轻松。",
  },
  {
    id: "lijiang",
    name: "丽江",
    province: "云南",
    longitude: 100.23,
    latitude: 26.87,
    visited: true,
    labelPosition: "above",
    memoryType: "旧城与山水",
    story: "山、水与旧城在这里相遇，旅行的节奏也随之慢下来。",
  },
  {
    id: "dali",
    name: "大理",
    province: "云南",
    longitude: 100.27,
    latitude: 25.61,
    visited: true,
    labelPosition: "right",
    memoryType: "风与湖面",
    story: "风、湖面与远山，构成了一段开放而安静的记忆。",
  },
  {
    id: "beijing",
    name: "北京",
    province: "北京",
    longitude: 116.41,
    latitude: 39.90,
    visited: true,
    labelPosition: "left",
    memoryType: "学习与生活",
    story: "学习、生活与研究交叠在一起，许多新的阶段从这里开始。",
  },
  { id: "taiyuan", name: "太原", province: "山西", longitude: 112.55, latitude: 37.87, visited: false },
  { id: "shenyang", name: "沈阳", province: "辽宁", longitude: 123.43, latitude: 41.81, visited: false },
  { id: "harbin", name: "哈尔滨", province: "黑龙江", longitude: 126.64, latitude: 45.76, visited: false },
  {
    id: "shanghai",
    name: "上海",
    province: "上海",
    longitude: 121.47,
    latitude: 31.23,
    visited: true,
    labelPosition: "right",
    memoryType: "城市观察",
    story: "密集的街道、夜色与江风，让这座城市显得清晰又遥远。",
  },
  {
    id: "qingdao",
    name: "青岛",
    province: "山东",
    longitude: 120.38,
    latitude: 36.07,
    visited: true,
    labelPosition: "right",
    memoryType: "海边城市",
    story: "海风、坡路与红瓦屋顶，是这座城市留下的第一层记忆。",
  },
  {
    id: "linyi",
    name: "临沂",
    province: "山东",
    longitude: 118.36,
    latitude: 35.10,
    visited: true,
    labelPosition: "left",
    memoryType: "城市日常",
    story: "熟悉的生活气息，让每一次抵达都更接近日常本身。",
  },
  { id: "nanjing", name: "南京", province: "江苏", longitude: 118.80, latitude: 32.06, visited: false },
  {
    id: "hefei",
    name: "合肥",
    province: "安徽",
    longitude: 117.23,
    latitude: 31.82,
    visited: true,
    labelPosition: "above",
    memoryType: "短暂停留",
    story: "一次停留，记住了城市克制而平稳的生活节奏。",
  },
  {
    id: "hangzhou",
    name: "杭州",
    province: "浙江",
    longitude: 120.16,
    latitude: 30.27,
    visited: true,
    labelPosition: "right",
    memoryType: "湖与城市",
    story: "湖水与城市并置，喧闹之外仍有可以慢下来的空间。",
  },
  {
    id: "huangshan",
    name: "黄山",
    province: "安徽",
    longitude: 118.34,
    latitude: 29.72,
    visited: true,
    labelPosition: "left",
    memoryType: "山中行走",
    story: "真正进入山中后，记忆由道路、云雾和体力共同组成。",
  },
  { id: "wuhan", name: "武汉", province: "湖北", longitude: 114.31, latitude: 30.59, visited: false },
  { id: "changsha", name: "长沙", province: "湖南", longitude: 112.94, latitude: 28.23, visited: false },
  { id: "xiamen", name: "厦门", province: "福建", longitude: 118.09, latitude: 24.48, visited: false },
  { id: "guangzhou", name: "广州", province: "广东", longitude: 113.26, latitude: 23.13, visited: false },
  { id: "hong-kong", name: "香港", province: "香港", longitude: 114.17, latitude: 22.32, visited: false },
  { id: "haikou", name: "海口", province: "海南", longitude: 110.20, latitude: 20.04, visited: false },
];

export const visitedCityCount = chinaCities.filter((city) => city.visited).length;
